import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

/**
 * Shows a native desktop dialog using Windows PowerShell + Windows.Forms.
 *
 * Encoding strategy (triple-safe):
 * 1. PS1 file written with UTF-8 BOM so PowerShell 5.1 reads it as UTF-8
 * 2. All Chinese text passed as Base64 inside the script
 * 3. Result written as Base64 (pure ASCII) to temp file, decoded by Node.js
 *
 * On non-Windows platforms, falls back to a terminal-based prompt.
 */
export async function showNativeDialog(
  message: string,
  suggestions: string[] = [],
): Promise<{ action: "accept" | "cancel"; text: string }> {
  if (process.platform === "win32") {
    return showPowerShellDialog(message, suggestions);
  }
  return showStdinDialog(message);
}

// ─── Windows: PowerShell + Windows.Forms ────────────────────

async function showPowerShellDialog(
  message: string,
  suggestions: string[],
): Promise<{ action: "accept" | "cancel"; text: string }> {
  const tmpDir = os.tmpdir();
  const id = `${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const resultFile = path.join(tmpDir, `chathook_result_${id}.txt`);

  // Encode all Chinese text as Base64 — zero encoding risk
  const messageB64 = Buffer.from(message, "utf-8").toString("base64");
  const suggestionB64s = suggestions.map((s) =>
    Buffer.from(s, "utf-8").toString("base64"),
  );

  // Result path with escaped backslashes for PowerShell string
  const psResultPath = resultFile.replace(/\\/g, "\\");

  // Build suggestion button code
  let suggestionCode = "";
  if (suggestionB64s.length > 0) {
    suggestionCode = `
    $suggestionPanel = New-Object System.Windows.Forms.FlowLayoutPanel
    $suggestionPanel.AutoSize = $true
    $suggestionPanel.AutoSizeMode = 'GrowAndShrink'
    $suggestionPanel.FlowDirection = 'LeftToRight'
    $suggestionPanel.WrapContents = $true
    $suggestionPanel.Padding = New-Object System.Windows.Forms.Padding(0,0,0,8)`;

    suggestionB64s.forEach((b64, i) => {
      suggestionCode += `
    $sugText${i} = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('${b64}'))
    $btn${i} = New-Object System.Windows.Forms.Button
    $btn${i}.Text = $sugText${i}
    $btn${i}.FlatStyle = 'Flat'
    $btn${i}.BackColor = [System.Drawing.Color]::FromArgb(69,71,90)
    $btn${i}.ForeColor = [System.Drawing.Color]::FromArgb(205,214,244)
    $btn${i}.Font = $smallFont
    $btn${i}.Padding = New-Object System.Windows.Forms.Padding(10,3,10,3)
    $btn${i}.Cursor = 'Hand'
    $btnVar${i} = $sugText${i}
    $btn${i}.Add_Click({ $inputBox.Text = $btnVar${i} })
    $suggestionPanel.Controls.Add($btn${i})`;
    });

    suggestionCode += `
    $suggestionPanel.Location = New-Object System.Drawing.Point(20, $yOffset)
    $form.Controls.Add($suggestionPanel)
    $yOffset += 40`;
  }

  // Build the full PowerShell script — only ASCII + Base64, no raw Chinese
  const psScript = `# chathook dialog - generated by Node.js
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# Decode message from Base64
$msgText = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('${messageB64}'))

$form = New-Object System.Windows.Forms.Form
$form.Text = 'chathook'
$form.Size = New-Object System.Drawing.Size(540, 500)
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedDialog'
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.BackColor = [System.Drawing.Color]::FromArgb(30,30,46)
$form.ForeColor = [System.Drawing.Color]::FromArgb(205,214,244)
$form.Font = New-Object System.Drawing.Font('Segoe UI', 9)

$smallFont = New-Object System.Drawing.Font('Segoe UI', 8)

# Header
$headerLabel = New-Object System.Windows.Forms.Label
$headerLabel.Text = 'chathook'
$headerLabel.Font = New-Object System.Drawing.Font('Segoe UI', 12, [System.Drawing.FontStyle]::Bold)
$headerLabel.ForeColor = [System.Drawing.Color]::FromArgb(137,180,250)
$headerLabel.AutoSize = $true
$headerLabel.Location = New-Object System.Drawing.Point(20, 15)
$form.Controls.Add($headerLabel)

# Message
$msgLabel = New-Object System.Windows.Forms.Label
$msgLabel.Text = $msgText
$msgLabel.AutoSize = $false
$msgLabel.Width = 490
$msgLabel.Height = 120
$msgLabel.Location = New-Object System.Drawing.Point(20, 50)
$msgLabel.BackColor = [System.Drawing.Color]::FromArgb(49,50,68)
$msgLabel.ForeColor = [System.Drawing.Color]::FromArgb(205,214,244)
$msgLabel.Padding = New-Object System.Windows.Forms.Padding(12,10,12,10)
$form.Controls.Add($msgLabel)

$yOffset = 180
${suggestionCode}

# Input textbox
$inputBox = New-Object System.Windows.Forms.TextBox
$inputBox.Multiline = $true
$inputBox.Size = New-Object System.Drawing.Size(490, 120)
$inputBox.Location = New-Object System.Drawing.Point(20, $yOffset)
$inputBox.BackColor = [System.Drawing.Color]::FromArgb(49,50,68)
$inputBox.ForeColor = [System.Drawing.Color]::FromArgb(205,214,244)
$inputBox.BorderStyle = 'FixedSingle'
$inputBox.Font = New-Object System.Drawing.Font('Segoe UI', 10)
$form.Controls.Add($inputBox)

$yOffset += 130

# Result file path
$resultPath = '${psResultPath}'

# Function to write result as Base64 (pure ASCII, zero encoding issues)
function WriteResult($text, $isCancel) {
    if ($isCancel) {
        [System.IO.File]::WriteAllText($resultPath, 'CANCEL', [System.Text.Encoding]::ASCII)
    } else {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)
        $b64 = [System.Convert]::ToBase64String($bytes)
        [System.IO.File]::WriteAllText($resultPath, $b64, [System.Text.Encoding]::ASCII)
    }
}

# Buttons
$btnPanel = New-Object System.Windows.Forms.Panel
$btnPanel.Size = New-Object System.Drawing.Size(490, 35)
$btnPanel.Location = New-Object System.Drawing.Point(20, $yOffset)
$btnPanel.BackColor = [System.Drawing.Color]::FromArgb(30,30,46)

$cancelBtn = New-Object System.Windows.Forms.Button
$cancelBtn.Text = 'Cancel'
$cancelBtn.Size = New-Object System.Drawing.Size(80, 32)
$cancelBtn.Location = New-Object System.Drawing.Point(305, 0)
$cancelBtn.FlatStyle = 'Flat'
$cancelBtn.BackColor = [System.Drawing.Color]::FromArgb(30,30,46)
$cancelBtn.ForeColor = [System.Drawing.Color]::FromArgb(243,139,168)
$cancelBtn.Cursor = 'Hand'
$cancelBtn.Add_Click({
    WriteResult '' $true
    $form.Close()
})

$submitBtn = New-Object System.Windows.Forms.Button
$submitBtn.Text = 'Submit'
$submitBtn.Size = New-Object System.Drawing.Size(90, 32)
$submitBtn.Location = New-Object System.Drawing.Point(395, 0)
$submitBtn.FlatStyle = 'Flat'
$submitBtn.BackColor = [System.Drawing.Color]::FromArgb(137,180,250)
$submitBtn.ForeColor = [System.Drawing.Color]::FromArgb(30,30,46)
$submitBtn.Font = New-Object System.Drawing.Font('Segoe UI', 9, [System.Drawing.FontStyle]::Bold)
$submitBtn.Cursor = 'Hand'
$submitBtn.Add_Click({
    WriteResult $inputBox.Text $false
    $form.Close()
})

$btnPanel.Controls.Add($cancelBtn)
$btnPanel.Controls.Add($submitBtn)
$form.Controls.Add($btnPanel)

# Ctrl+Enter to submit
$inputBox.Add_KeyDown({
    if ($_.Control -and $_.KeyCode -eq 'Enter') {
        WriteResult $inputBox.Text $false
        $form.Close()
    }
})

# Handle X button close
$form.Add_FormClosing({
    if (-not (Test-Path $resultPath)) {
        WriteResult '' $true
    }
})

$form.Activate()
$inputBox.Focus()
$form.ShowDialog() | Out-Null
`;

  // Write PS1 file with UTF-8 BOM so PowerShell 5.1 reads it correctly
  const psFile = path.join(tmpDir, `chathook_dialog_${id}.ps1`);
  const bom = Buffer.from([0xef, 0xbb, 0xbf]);
  const scriptBuf = Buffer.from(psScript, "utf-8");
  fs.writeFileSync(psFile, Buffer.concat([bom, scriptBuf]));

  try {
    await new Promise<void>((resolve, reject) => {
      const proc = spawn(
        "powershell.exe",
        [
          "-NoProfile",
          "-NonInteractive",
          "-ExecutionPolicy", "Bypass",
          "-File", psFile,
        ],
        {
          shell: false,
          stdio: "ignore",
        },
      );
      proc.on("close", () => resolve());
      proc.on("error", (err) => reject(err));
    });

    // Read result (pure ASCII: either "CANCEL" or Base64 string)
    if (fs.existsSync(resultFile)) {
      const raw = fs.readFileSync(resultFile, "ascii").trim();

      if (raw === "CANCEL") {
        return { action: "cancel", text: "" };
      }

      // Decode Base64 → UTF-8
      const text = Buffer.from(raw, "base64").toString("utf-8");
      return { action: "accept", text };
    }

    return { action: "cancel", text: "" };
  } finally {
    try {
      if (fs.existsSync(psFile)) fs.unlinkSync(psFile);
      if (fs.existsSync(resultFile)) fs.unlinkSync(resultFile);
    } catch {
      // ignore
    }
  }
}

// ─── Non-Windows fallback: stdin ────────────────────────────

async function showStdinDialog(
  message: string,
): Promise<{ action: "accept" | "cancel"; text: string }> {
  return new Promise((resolve) => {
    process.stderr.write(`\n[chathook] ${message}\n`);
    process.stderr.write(
      `[chathook] Enter your response (or type __cancel__ to cancel):\n> `,
    );
    process.stdin.resume();
    process.stdin.once("data", (data) => {
      process.stdin.pause();
      const text = data.toString().trim();
      if (text === "__cancel__" || text === "") {
        resolve({ action: "cancel", text: "" });
      } else {
        resolve({ action: "accept", text });
      }
    });
  });
}
